"""
Django settings for drchrono_happy_birthday project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o_5vnb5l)x-&cmxy$b68dzxtb9@9xiv*t(o@=m&(t%vowb#@ht'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'happybirthday',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'drchrono_happy_birthday.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drchrono_happy_birthday.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


AUTH_USER_MODEL = 'happybirthday.Doctor'

OPTION_TO_UPDATE = 'update'
OPTION_TO_RESET = 'reset'

PATIENTS_SCOPE = 'patients'
USER_SCOPE = 'user'
CODE_TO_TOKEN_URL = "https://drchrono.com/o/token/"
DOCTOR_API_URL = "https://drchrono.com/api/doctors"
PATIENTS_API_URL = "https://drchrono.com/api/patients"
DRCHRONO_CLIENT_ID = ''
DRCHRONO_CLIENT_SECRET = ''

MAILGUN_SECRET_KEY = ''
MAILGUN_PUBLIC_KEY = ''
MAILGUN_API_URL = ''

DEFAULT_PASSWORD = 'doctor123'

#task queue
import djcelery
from celery.schedules import crontab
djcelery.setup_loader()

from datetime import timedelta

CELERYBEAT_SCHEDULE = {
    'add-every-morning': {
        'task': 'happybirthday.tasks.debug_task',
        'schedule': crontab(hour=7, minute=30)
    },
    'update-patients':  {
        'task': 'happybirthday.tasks.update_records',
        'schedule': timedelta(hours=5)
    }
}
BROKER_URL = "amqp://admin:admin@localhost:5672/default"
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
CELERY_BEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TIMEZONE = 'America/Los_Angeles'

SITE_URL = ''
OAUTH_HANDLER_USER = '/oauth_handler_user/'
OAUTH_HANDLER_PATIENT = '/oauth_handler_patient/'

DEFAULT_USER_PASSWORD = 'drchrono123'

